### ISSUE TITLE
Still works?

### ISSUE THREAD

**Issue by junhyukso** [delta-kor/kakao-message-template#3]
is it still works in node-kakao v3 ? (https://github.com/storycraft/node-kakao)

**Comment by delta-kor** [comment]
This doesn't work since monkey attack.
It might work after changing the service id in the source code even with n.k. v3.

[https://www.github.com/delta-kor/kakao-message-template/tree/master/src/components/KakaoLinkInfo.ts](https://www.github.com/delta-kor/kakao-message-template/tree/master/src/components/KakaoLinkInfo.ts)
